# Generated by Django 6.0.3 on 2026-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('apparent_temperature_max', models.FloatField()),
                ('apparent_temperature_min', models.FloatField()),
                ('weather_code', models.IntegerField()),
                ('wind_speed_max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weather_records',
                'ordering': ['-date'],
            },
        ),
    ]
