# Generated by Django 6.0.3 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(
                fields=('date', 'latitude', 'longitude'),
                name='unique_weather_record_per_date_and_location',
            ),
        ),
    ]
