CREATE TABLE IF NOT EXISTS weather_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    temperature_max DOUBLE PRECISION NOT NULL,
    temperature_min DOUBLE PRECISION NOT NULL,
    apparent_temperature_max DOUBLE PRECISION NOT NULL,
    apparent_temperature_min DOUBLE PRECISION NOT NULL,
    weather_code INTEGER NOT NULL,
    wind_speed_max DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_weather_record_per_date_and_location
        UNIQUE (date, latitude, longitude)
);
